In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

1

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([5, 6, 7, 8, 9])

In [11]:
arr[0:5]=100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [13]:
arr =np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr= arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:]=99

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
 arr_copy= arr.copy()

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy[:]=100

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
#indexing a 2d array aka a matrix

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0][0]

5

In [31]:
arr_2d[0][2]

15

In [32]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[1,2]

30

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])