In [1]:
#numy arrays come in one dimensions vectors or two dimensional matrices

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
arr = np.array([1,2,3])

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
 np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
 np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
 np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
#identity matrix

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.98597351, 0.35184871, 0.99263401, 0.52613255, 0.26208583])

In [ ]:
#^uniform distrobution

In [24]:
np.random.rand(5,5)

array([[0.76102148, 0.94777854, 0.27851413, 0.43432875, 0.95177929],
       [0.09130775, 0.20581192, 0.06232396, 0.10586197, 0.32115037],
       [0.83626395, 0.18385114, 0.24468044, 0.34378686, 0.08583738],
       [0.63020896, 0.21216111, 0.12170159, 0.37287656, 0.70927136],
       [0.11883933, 0.91967149, 0.75587106, 0.15363271, 0.22677251]])

In [25]:
#below uses a standard distrobution

In [26]:
np.random.randn(2)

array([1.13744195, 0.47238659])

In [28]:
np.random.randn(4,4)

array([[ 0.25762705,  1.27005559,  0.06267147,  1.15845782],
       [-0.18405441,  0.515564  ,  1.05418455,  0.02165277],
       [-0.76840945,  0.15939014, -0.14726941, -0.20487891],
       [ 1.18191141,  0.64942464,  1.29535752,  0.24726904]])

In [29]:
#returns random intergers from low to high number

In [30]:
np.random.randint(1,100)

84

In [31]:
np.random.randint(1,100,10)

array([85, 96, 24, 34, 99, 95, 33, 76, 65, 87])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([48, 37, 49, 44, 43, 29, 23, 48, 32,  1])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([48, 37, 49, 44, 43, 29, 23, 48, 32,  1])

In [39]:
#find the max value in array

In [40]:
ranarr.max()

49

In [41]:
ranarr.min()

1

In [42]:
#find what index these values are in

In [43]:
ranarr.argmax()

2

In [44]:
#the max value is in the second index

In [45]:
#find the shape of a vector

In [47]:
arr.shape


(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr.shape

(5, 5)

In [52]:
arr.dtype

dtype('int32')

In [53]:
#shows the arrays data type

In [54]:
from numpy.random import randint 

In [55]:
randint(2,10)

3